/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DailyReportBatchEntry = IDL.Record({
  'todayProduction' : IDL.Nat,
  'totalCompleted' : IDL.Nat,
  'date' : IDL.Text,
  'operationName' : IDL.Text,
  'dispatched' : IDL.Nat,
  'inHand' : IDL.Nat,
});
export const ContainerType = IDL.Variant({
  'flatPack' : IDL.Null,
  'fullContainer' : IDL.Null,
  'insulated' : IDL.Null,
});
export const Time = IDL.Int;
export const Shift = IDL.Record({
  'name' : IDL.Text,
  'containerQty' : IDL.Nat,
  'shiftId' : IDL.Nat,
});
export const ContainerStatus = IDL.Variant({
  'readyForDispatch' : IDL.Null,
  'pendingOperations' : IDL.Null,
  'underTesting' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'department' : IDL.Text,
});
export const FrontendContainerSizes = IDL.Record({
  'id' : IDL.Nat,
  'container_size' : IDL.Text,
  'is_high_cube' : IDL.Bool,
  'length_ft' : IDL.Nat,
  'height_ft' : IDL.Float64,
  'width_ft' : IDL.Nat,
  'is_active' : IDL.Bool,
});
export const ContainerTypes = IDL.Record({
  'id' : IDL.Nat,
  'description' : IDL.Text,
  'container_type_name' : IDL.Text,
  'is_active' : IDL.Bool,
});
export const DailyProductionReport = IDL.Record({
  'id' : IDL.Nat,
  'container_type_id' : IDL.Nat,
  'todayProduction' : IDL.Nat,
  'totalCompleted' : IDL.Nat,
  'container_size_id' : IDL.Nat,
  'date' : IDL.Text,
  'operationName' : IDL.Text,
  'dispatched' : IDL.Nat,
  'inHand' : IDL.Nat,
});
export const DispatchEntry = IDL.Record({
  'destination' : IDL.Text,
  'createdAt' : Time,
  'dispatchId' : IDL.Nat,
  'dispatchDate' : Time,
  'deliveryStatus' : IDL.Text,
  'containerType' : ContainerType,
  'quantity' : IDL.Nat,
});
export const EnhancedMasterOrderStatus = IDL.Record({
  'id' : IDL.Nat,
  'totalDispatched' : IDL.Nat,
  'totalManufactured' : IDL.Nat,
  'completionPercentage' : IDL.Float64,
  'orderName' : IDL.Text,
  'remainingToProduce' : IDL.Nat,
  'totalOrderQuantity' : IDL.Nat,
  'finishedStock' : IDL.Nat,
});
export const ProductionEntry = IDL.Record({
  'status' : ContainerStatus,
  'modifiedAt' : Time,
  'createdAt' : Time,
  'totalQty' : IDL.Nat,
  'entryId' : IDL.Nat,
  'containerType' : ContainerType,
  'statusTime' : Time,
  'shiftDetail' : Shift,
});
export const HistoricalOpeningBalance = IDL.Record({
  'id' : IDL.Nat,
  'manufacturingStartDate' : IDL.Text,
  'dispatchedBeforeSystem' : IDL.Nat,
  'systemGoLiveDate' : IDL.Text,
  'entryType' : IDL.Text,
  'openingDate' : IDL.Text,
  'manufacturedBeforeSystem' : IDL.Nat,
  'isLocked' : IDL.Bool,
});
export const MasterOrderStatus = IDL.Record({
  'id' : IDL.Nat,
  'totalDispatched' : IDL.Nat,
  'totalManufactured' : IDL.Nat,
  'orderName' : IDL.Text,
  'totalOrderQuantity' : IDL.Nat,
});
export const MonthlyProductionTotals = IDL.Record({
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'totalContainers' : IDL.Nat,
});
export const OperationStatus = IDL.Record({
  'pendingCount' : IDL.Nat,
  'operation' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'batchUpdateDailyProductionReport' : IDL.Func(
      [IDL.Text, IDL.Vec(DailyReportBatchEntry)],
      [],
      [],
    ),
  'createDailyProductionReport' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'createDispatchEntry' : IDL.Func(
      [ContainerType, IDL.Nat, Time, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createHistoricalOpeningBalance' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createProductionEntry' : IDL.Func(
      [ContainerType, Shift, ContainerStatus, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContainerSizes' : IDL.Func(
      [],
      [IDL.Vec(FrontendContainerSizes)],
      ['query'],
    ),
  'getContainerStatuses' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ContainerType, ContainerStatus))],
      ['query'],
    ),
  'getContainerTypes' : IDL.Func([], [IDL.Vec(ContainerTypes)], ['query']),
  'getDailyProductionByStatus' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ContainerType, ContainerStatus, IDL.Nat))],
      ['query'],
    ),
  'getDailyProductionReportsByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DailyProductionReport)],
      ['query'],
    ),
  'getDailyProductionReportsByDateRange' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Tuple(IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat))],
      [IDL.Vec(DailyProductionReport)],
      ['query'],
    ),
  'getDailyProductionReportsByOperation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DailyProductionReport)],
      ['query'],
    ),
  'getDispatchEntriesByDate' : IDL.Func(
      [Time, Time],
      [IDL.Vec(DispatchEntry)],
      ['query'],
    ),
  'getEnhancedMasterOrderStatus' : IDL.Func(
      [],
      [EnhancedMasterOrderStatus],
      ['query'],
    ),
  'getFilteredProductionEntries' : IDL.Func(
      [IDL.Opt(ContainerType), IDL.Opt(ContainerStatus)],
      [IDL.Vec(ProductionEntry)],
      ['query'],
    ),
  'getHistoricalOpeningBalance' : IDL.Func(
      [],
      [IDL.Opt(HistoricalOpeningBalance)],
      ['query'],
    ),
  'getMasterOrderStatus' : IDL.Func([], [MasterOrderStatus], ['query']),
  'getMonthlyProductionTotals' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [MonthlyProductionTotals],
      ['query'],
    ),
  'getOperationWorkloadSummary' : IDL.Func(
      [],
      [IDL.Vec(OperationStatus)],
      ['query'],
    ),
  'getProductionSummaryByType' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Tuple(IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat))],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeContainerTypesAndSizes' : IDL.Func([], [], []),
  'initializeProductionReports' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitOrUpdateDailyReport' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'updateDailyProductionReport' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateDailyProductionReportById' : IDL.Func(
      [
        IDL.Nat,
        IDL.Tuple(IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)),
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'updateDispatchStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateMasterOrderStatus' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateProductionStatus' : IDL.Func([IDL.Nat, ContainerStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DailyReportBatchEntry = IDL.Record({
    'todayProduction' : IDL.Nat,
    'totalCompleted' : IDL.Nat,
    'date' : IDL.Text,
    'operationName' : IDL.Text,
    'dispatched' : IDL.Nat,
    'inHand' : IDL.Nat,
  });
  const ContainerType = IDL.Variant({
    'flatPack' : IDL.Null,
    'fullContainer' : IDL.Null,
    'insulated' : IDL.Null,
  });
  const Time = IDL.Int;
  const Shift = IDL.Record({
    'name' : IDL.Text,
    'containerQty' : IDL.Nat,
    'shiftId' : IDL.Nat,
  });
  const ContainerStatus = IDL.Variant({
    'readyForDispatch' : IDL.Null,
    'pendingOperations' : IDL.Null,
    'underTesting' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'department' : IDL.Text,
  });
  const FrontendContainerSizes = IDL.Record({
    'id' : IDL.Nat,
    'container_size' : IDL.Text,
    'is_high_cube' : IDL.Bool,
    'length_ft' : IDL.Nat,
    'height_ft' : IDL.Float64,
    'width_ft' : IDL.Nat,
    'is_active' : IDL.Bool,
  });
  const ContainerTypes = IDL.Record({
    'id' : IDL.Nat,
    'description' : IDL.Text,
    'container_type_name' : IDL.Text,
    'is_active' : IDL.Bool,
  });
  const DailyProductionReport = IDL.Record({
    'id' : IDL.Nat,
    'container_type_id' : IDL.Nat,
    'todayProduction' : IDL.Nat,
    'totalCompleted' : IDL.Nat,
    'container_size_id' : IDL.Nat,
    'date' : IDL.Text,
    'operationName' : IDL.Text,
    'dispatched' : IDL.Nat,
    'inHand' : IDL.Nat,
  });
  const DispatchEntry = IDL.Record({
    'destination' : IDL.Text,
    'createdAt' : Time,
    'dispatchId' : IDL.Nat,
    'dispatchDate' : Time,
    'deliveryStatus' : IDL.Text,
    'containerType' : ContainerType,
    'quantity' : IDL.Nat,
  });
  const EnhancedMasterOrderStatus = IDL.Record({
    'id' : IDL.Nat,
    'totalDispatched' : IDL.Nat,
    'totalManufactured' : IDL.Nat,
    'completionPercentage' : IDL.Float64,
    'orderName' : IDL.Text,
    'remainingToProduce' : IDL.Nat,
    'totalOrderQuantity' : IDL.Nat,
    'finishedStock' : IDL.Nat,
  });
  const ProductionEntry = IDL.Record({
    'status' : ContainerStatus,
    'modifiedAt' : Time,
    'createdAt' : Time,
    'totalQty' : IDL.Nat,
    'entryId' : IDL.Nat,
    'containerType' : ContainerType,
    'statusTime' : Time,
    'shiftDetail' : Shift,
  });
  const HistoricalOpeningBalance = IDL.Record({
    'id' : IDL.Nat,
    'manufacturingStartDate' : IDL.Text,
    'dispatchedBeforeSystem' : IDL.Nat,
    'systemGoLiveDate' : IDL.Text,
    'entryType' : IDL.Text,
    'openingDate' : IDL.Text,
    'manufacturedBeforeSystem' : IDL.Nat,
    'isLocked' : IDL.Bool,
  });
  const MasterOrderStatus = IDL.Record({
    'id' : IDL.Nat,
    'totalDispatched' : IDL.Nat,
    'totalManufactured' : IDL.Nat,
    'orderName' : IDL.Text,
    'totalOrderQuantity' : IDL.Nat,
  });
  const MonthlyProductionTotals = IDL.Record({
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'totalContainers' : IDL.Nat,
  });
  const OperationStatus = IDL.Record({
    'pendingCount' : IDL.Nat,
    'operation' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'batchUpdateDailyProductionReport' : IDL.Func(
        [IDL.Text, IDL.Vec(DailyReportBatchEntry)],
        [],
        [],
      ),
    'createDailyProductionReport' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'createDispatchEntry' : IDL.Func(
        [ContainerType, IDL.Nat, Time, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createHistoricalOpeningBalance' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createProductionEntry' : IDL.Func(
        [ContainerType, Shift, ContainerStatus, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContainerSizes' : IDL.Func(
        [],
        [IDL.Vec(FrontendContainerSizes)],
        ['query'],
      ),
    'getContainerStatuses' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ContainerType, ContainerStatus))],
        ['query'],
      ),
    'getContainerTypes' : IDL.Func([], [IDL.Vec(ContainerTypes)], ['query']),
    'getDailyProductionByStatus' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ContainerType, ContainerStatus, IDL.Nat))],
        ['query'],
      ),
    'getDailyProductionReportsByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DailyProductionReport)],
        ['query'],
      ),
    'getDailyProductionReportsByDateRange' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Tuple(IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat))],
        [IDL.Vec(DailyProductionReport)],
        ['query'],
      ),
    'getDailyProductionReportsByOperation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DailyProductionReport)],
        ['query'],
      ),
    'getDispatchEntriesByDate' : IDL.Func(
        [Time, Time],
        [IDL.Vec(DispatchEntry)],
        ['query'],
      ),
    'getEnhancedMasterOrderStatus' : IDL.Func(
        [],
        [EnhancedMasterOrderStatus],
        ['query'],
      ),
    'getFilteredProductionEntries' : IDL.Func(
        [IDL.Opt(ContainerType), IDL.Opt(ContainerStatus)],
        [IDL.Vec(ProductionEntry)],
        ['query'],
      ),
    'getHistoricalOpeningBalance' : IDL.Func(
        [],
        [IDL.Opt(HistoricalOpeningBalance)],
        ['query'],
      ),
    'getMasterOrderStatus' : IDL.Func([], [MasterOrderStatus], ['query']),
    'getMonthlyProductionTotals' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [MonthlyProductionTotals],
        ['query'],
      ),
    'getOperationWorkloadSummary' : IDL.Func(
        [],
        [IDL.Vec(OperationStatus)],
        ['query'],
      ),
    'getProductionSummaryByType' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Tuple(IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat))],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeContainerTypesAndSizes' : IDL.Func([], [], []),
    'initializeProductionReports' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitOrUpdateDailyReport' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'updateDailyProductionReport' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateDailyProductionReportById' : IDL.Func(
        [
          IDL.Nat,
          IDL.Tuple(IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)),
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'updateDispatchStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateMasterOrderStatus' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateProductionStatus' : IDL.Func([IDL.Nat, ContainerStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };