/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ContainerStatus = { 'readyForDispatch' : null } |
  { 'pendingOperations' : null } |
  { 'underTesting' : null };
export type ContainerType = { 'flatPack' : null } |
  { 'fullContainer' : null } |
  { 'insulated' : null };
export interface DailyProductionReport {
  'id' : bigint,
  'despatched' : bigint,
  'todayProduction' : bigint,
  'totalCompleted' : bigint,
  'date' : string,
  'operationName' : string,
  'inHand' : bigint,
}
export interface DispatchEntry {
  'destination' : string,
  'createdAt' : Time,
  'dispatchId' : bigint,
  'dispatchDate' : Time,
  'deliveryStatus' : string,
  'containerType' : ContainerType,
  'quantity' : bigint,
}
export interface MonthlyProductionTotals {
  'month' : bigint,
  'year' : bigint,
  'totalContainers' : bigint,
}
export interface OperationStatus {
  'pendingCount' : bigint,
  'operation' : string,
}
export interface ProductionEntry {
  'status' : ContainerStatus,
  'modifiedAt' : Time,
  'createdAt' : Time,
  'totalQty' : bigint,
  'entryId' : bigint,
  'containerType' : ContainerType,
  'statusTime' : Time,
  'shiftDetail' : Shift,
}
export interface Shift {
  'name' : string,
  'containerQty' : bigint,
  'shiftId' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : UserRole,
  'department' : string,
}
export type UserRole = { 'Viewer' : null } |
  { 'Admin' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createDailyProductionReport' : ActorMethod<
    [string, string, bigint, bigint, bigint, bigint],
    bigint
  >,
  'createDispatchEntry' : ActorMethod<
    [ContainerType, bigint, Time, string, string],
    bigint
  >,
  'createProductionEntry' : ActorMethod<
    [ContainerType, Shift, ContainerStatus, bigint],
    bigint
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getContainerStatuses' : ActorMethod<
    [],
    Array<[ContainerType, ContainerStatus]>
  >,
  'getDailyProductionByStatus' : ActorMethod<
    [],
    Array<[ContainerType, ContainerStatus, bigint]>
  >,
  'getDailyProductionReportsByDate' : ActorMethod<
    [string],
    Array<DailyProductionReport>
  >,
  'getDailyProductionReportsByDateRange' : ActorMethod<
    [string, string],
    Array<DailyProductionReport>
  >,
  'getDailyProductionReportsByOperation' : ActorMethod<
    [string],
    Array<DailyProductionReport>
  >,
  'getDispatchEntriesByDate' : ActorMethod<[Time, Time], Array<DispatchEntry>>,
  'getFilteredProductionEntries' : ActorMethod<
    [[] | [ContainerType], [] | [ContainerStatus]],
    Array<ProductionEntry>
  >,
  'getMonthlyProductionTotals' : ActorMethod<
    [bigint, bigint],
    MonthlyProductionTotals
  >,
  'getOperationWorkloadSummary' : ActorMethod<[], Array<OperationStatus>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeProductionReports' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitOrUpdateDailyReport' : ActorMethod<
    [string, string, bigint, bigint, bigint, bigint],
    bigint
  >,
  'updateDailyProductionReport' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint],
    undefined
  >,
  'updateDailyProductionReportById' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint],
    undefined
  >,
  'updateDispatchStatus' : ActorMethod<[bigint, string], undefined>,
  'updateProductionStatus' : ActorMethod<[bigint, ContainerStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];