/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContainerType = IDL.Variant({
  'flatPack' : IDL.Null,
  'fullContainer' : IDL.Null,
  'insulated' : IDL.Null,
});
export const Time = IDL.Int;
export const Shift = IDL.Record({
  'name' : IDL.Text,
  'containerQty' : IDL.Nat,
  'shiftId' : IDL.Nat,
});
export const ContainerStatus = IDL.Variant({
  'readyForDispatch' : IDL.Null,
  'pendingOperations' : IDL.Null,
  'underTesting' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'Viewer' : IDL.Null,
  'Admin' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : UserRole,
  'department' : IDL.Text,
});
export const DailyProductionReport = IDL.Record({
  'id' : IDL.Nat,
  'despatched' : IDL.Nat,
  'todayProduction' : IDL.Nat,
  'totalCompleted' : IDL.Nat,
  'date' : IDL.Text,
  'operationName' : IDL.Text,
  'inHand' : IDL.Nat,
});
export const DispatchEntry = IDL.Record({
  'destination' : IDL.Text,
  'createdAt' : Time,
  'dispatchId' : IDL.Nat,
  'dispatchDate' : Time,
  'deliveryStatus' : IDL.Text,
  'containerType' : ContainerType,
  'quantity' : IDL.Nat,
});
export const ProductionEntry = IDL.Record({
  'status' : ContainerStatus,
  'modifiedAt' : Time,
  'createdAt' : Time,
  'totalQty' : IDL.Nat,
  'entryId' : IDL.Nat,
  'containerType' : ContainerType,
  'statusTime' : Time,
  'shiftDetail' : Shift,
});
export const MonthlyProductionTotals = IDL.Record({
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'totalContainers' : IDL.Nat,
});
export const OperationStatus = IDL.Record({
  'pendingCount' : IDL.Nat,
  'operation' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createDailyProductionReport' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createDispatchEntry' : IDL.Func(
      [ContainerType, IDL.Nat, Time, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createProductionEntry' : IDL.Func(
      [ContainerType, Shift, ContainerStatus, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getContainerStatuses' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ContainerType, ContainerStatus))],
      ['query'],
    ),
  'getDailyProductionByStatus' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ContainerType, ContainerStatus, IDL.Nat))],
      ['query'],
    ),
  'getDailyProductionReportsByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DailyProductionReport)],
      ['query'],
    ),
  'getDailyProductionReportsByDateRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(DailyProductionReport)],
      ['query'],
    ),
  'getDailyProductionReportsByOperation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DailyProductionReport)],
      ['query'],
    ),
  'getDispatchEntriesByDate' : IDL.Func(
      [Time, Time],
      [IDL.Vec(DispatchEntry)],
      ['query'],
    ),
  'getFilteredProductionEntries' : IDL.Func(
      [IDL.Opt(ContainerType), IDL.Opt(ContainerStatus)],
      [IDL.Vec(ProductionEntry)],
      ['query'],
    ),
  'getMonthlyProductionTotals' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [MonthlyProductionTotals],
      ['query'],
    ),
  'getOperationWorkloadSummary' : IDL.Func(
      [],
      [IDL.Vec(OperationStatus)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeProductionReports' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitOrUpdateDailyReport' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'updateDailyProductionReport' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateDailyProductionReportById' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateDispatchStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateProductionStatus' : IDL.Func([IDL.Nat, ContainerStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContainerType = IDL.Variant({
    'flatPack' : IDL.Null,
    'fullContainer' : IDL.Null,
    'insulated' : IDL.Null,
  });
  const Time = IDL.Int;
  const Shift = IDL.Record({
    'name' : IDL.Text,
    'containerQty' : IDL.Nat,
    'shiftId' : IDL.Nat,
  });
  const ContainerStatus = IDL.Variant({
    'readyForDispatch' : IDL.Null,
    'pendingOperations' : IDL.Null,
    'underTesting' : IDL.Null,
  });
  const UserRole = IDL.Variant({ 'Viewer' : IDL.Null, 'Admin' : IDL.Null });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : UserRole,
    'department' : IDL.Text,
  });
  const DailyProductionReport = IDL.Record({
    'id' : IDL.Nat,
    'despatched' : IDL.Nat,
    'todayProduction' : IDL.Nat,
    'totalCompleted' : IDL.Nat,
    'date' : IDL.Text,
    'operationName' : IDL.Text,
    'inHand' : IDL.Nat,
  });
  const DispatchEntry = IDL.Record({
    'destination' : IDL.Text,
    'createdAt' : Time,
    'dispatchId' : IDL.Nat,
    'dispatchDate' : Time,
    'deliveryStatus' : IDL.Text,
    'containerType' : ContainerType,
    'quantity' : IDL.Nat,
  });
  const ProductionEntry = IDL.Record({
    'status' : ContainerStatus,
    'modifiedAt' : Time,
    'createdAt' : Time,
    'totalQty' : IDL.Nat,
    'entryId' : IDL.Nat,
    'containerType' : ContainerType,
    'statusTime' : Time,
    'shiftDetail' : Shift,
  });
  const MonthlyProductionTotals = IDL.Record({
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'totalContainers' : IDL.Nat,
  });
  const OperationStatus = IDL.Record({
    'pendingCount' : IDL.Nat,
    'operation' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createDailyProductionReport' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createDispatchEntry' : IDL.Func(
        [ContainerType, IDL.Nat, Time, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createProductionEntry' : IDL.Func(
        [ContainerType, Shift, ContainerStatus, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getContainerStatuses' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ContainerType, ContainerStatus))],
        ['query'],
      ),
    'getDailyProductionByStatus' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ContainerType, ContainerStatus, IDL.Nat))],
        ['query'],
      ),
    'getDailyProductionReportsByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DailyProductionReport)],
        ['query'],
      ),
    'getDailyProductionReportsByDateRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(DailyProductionReport)],
        ['query'],
      ),
    'getDailyProductionReportsByOperation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DailyProductionReport)],
        ['query'],
      ),
    'getDispatchEntriesByDate' : IDL.Func(
        [Time, Time],
        [IDL.Vec(DispatchEntry)],
        ['query'],
      ),
    'getFilteredProductionEntries' : IDL.Func(
        [IDL.Opt(ContainerType), IDL.Opt(ContainerStatus)],
        [IDL.Vec(ProductionEntry)],
        ['query'],
      ),
    'getMonthlyProductionTotals' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [MonthlyProductionTotals],
        ['query'],
      ),
    'getOperationWorkloadSummary' : IDL.Func(
        [],
        [IDL.Vec(OperationStatus)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeProductionReports' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitOrUpdateDailyReport' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'updateDailyProductionReport' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateDailyProductionReportById' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateDispatchStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateProductionStatus' : IDL.Func([IDL.Nat, ContainerStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };