/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FrontendContainerSizes {
    id: bigint;
    container_size: string;
    is_high_cube: boolean;
    length_ft: bigint;
    height_ft: number;
    width_ft: bigint;
    is_active: boolean;
}
export interface ContainerTypes {
    id: bigint;
    description: string;
    container_type_name: string;
    is_active: boolean;
}
export type Time = bigint;
export interface EnhancedMasterOrderStatus {
    id: bigint;
    totalDispatched: bigint;
    totalManufactured: bigint;
    completionPercentage: number;
    orderName: string;
    remainingToProduce: bigint;
    totalOrderQuantity: bigint;
    finishedStock: bigint;
}
export interface Shift {
    name: string;
    containerQty: bigint;
    shiftId: bigint;
}
export interface MonthlyProductionTotals {
    month: bigint;
    year: bigint;
    totalContainers: bigint;
}
export interface HistoricalOpeningBalance {
    id: bigint;
    manufacturingStartDate: string;
    dispatchedBeforeSystem: bigint;
    systemGoLiveDate: string;
    entryType: string;
    openingDate: string;
    manufacturedBeforeSystem: bigint;
    isLocked: boolean;
}
export interface OperationStatus {
    pendingCount: bigint;
    operation: string;
}
export interface DispatchEntry {
    destination: string;
    createdAt: Time;
    dispatchId: bigint;
    dispatchDate: Time;
    deliveryStatus: string;
    containerType: ContainerType;
    quantity: bigint;
}
export interface ProductionEntry {
    status: ContainerStatus;
    modifiedAt: Time;
    createdAt: Time;
    totalQty: bigint;
    entryId: bigint;
    containerType: ContainerType;
    statusTime: Time;
    shiftDetail: Shift;
}
export interface DailyReportBatchEntry {
    todayProduction: bigint;
    totalCompleted: bigint;
    date: string;
    operationName: string;
    dispatched: bigint;
    inHand: bigint;
}
export interface MasterOrderStatus {
    id: bigint;
    totalDispatched: bigint;
    totalManufactured: bigint;
    orderName: string;
    totalOrderQuantity: bigint;
}
export interface DailyProductionReport {
    id: bigint;
    container_type_id: bigint;
    todayProduction: bigint;
    totalCompleted: bigint;
    container_size_id: bigint;
    date: string;
    operationName: string;
    dispatched: bigint;
    inHand: bigint;
}
export interface UserProfile {
    name: string;
    department: string;
}
export enum ContainerStatus {
    readyForDispatch = "readyForDispatch",
    pendingOperations = "pendingOperations",
    underTesting = "underTesting"
}
export enum ContainerType {
    flatPack = "flatPack",
    fullContainer = "fullContainer",
    insulated = "insulated"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    batchUpdateDailyProductionReport(date: string, operations: Array<DailyReportBatchEntry>): Promise<void>;
    createDailyProductionReport(date: string, operationName: string, containerTypeId: bigint, containerSizeId: bigint, todayProduction: bigint, totalCompleted: bigint, dispatched: bigint, inHand: bigint): Promise<bigint>;
    createDispatchEntry(containerType: ContainerType, quantity: bigint, dispatchDate: Time, destination: string, deliveryStatus: string): Promise<bigint>;
    createHistoricalOpeningBalance(openingDate: string, manufacturedBeforeSystem: bigint, dispatchedBeforeSystem: bigint, manufacturingStartDate: string, systemGoLiveDate: string): Promise<void>;
    createProductionEntry(containerType: ContainerType, shiftDetail: Shift, status: ContainerStatus, totalQty: bigint): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContainerSizes(): Promise<Array<FrontendContainerSizes>>;
    getContainerStatuses(): Promise<Array<[ContainerType, ContainerStatus]>>;
    getContainerTypes(): Promise<Array<ContainerTypes>>;
    getDailyProductionByStatus(): Promise<Array<[ContainerType, ContainerStatus, bigint]>>;
    getDailyProductionReportsByDate(date: string): Promise<Array<DailyProductionReport>>;
    getDailyProductionReportsByDateRange(startDate: string, endDate: string, containerFilters: [bigint | null, bigint | null]): Promise<Array<DailyProductionReport>>;
    getDailyProductionReportsByOperation(operationName: string): Promise<Array<DailyProductionReport>>;
    getDispatchEntriesByDate(_rangeStart: Time, _rangeEnd: Time): Promise<Array<DispatchEntry>>;
    getEnhancedMasterOrderStatus(): Promise<EnhancedMasterOrderStatus>;
    getFilteredProductionEntries(containerType: ContainerType | null, status: ContainerStatus | null): Promise<Array<ProductionEntry>>;
    getHistoricalOpeningBalance(): Promise<HistoricalOpeningBalance | null>;
    getMasterOrderStatus(): Promise<MasterOrderStatus>;
    getMonthlyProductionTotals(year: bigint, month: bigint): Promise<MonthlyProductionTotals>;
    getOperationWorkloadSummary(): Promise<Array<OperationStatus>>;
    getProductionSummaryByType(startDate: string, endDate: string, containerFilters: [bigint | null, bigint | null]): Promise<Array<[bigint, bigint, bigint, bigint, bigint]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeContainerTypesAndSizes(): Promise<void>;
    initializeProductionReports(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitOrUpdateDailyReport(date: string, operationName: string, containerTypeId: bigint, containerSizeId: bigint, todayProduction: bigint, totalCompleted: bigint, dispatched: bigint, inHand: bigint): Promise<bigint>;
    updateDailyProductionReport(_id: bigint, _todayProduction: bigint, _totalCompleted: bigint, _dispatched: bigint, _inHand: bigint): Promise<void>;
    updateDailyProductionReportById(reportId: bigint, containerFilters: [bigint | null, bigint | null], todayProduction: bigint, totalCompleted: bigint, dispatched: bigint, inHand: bigint): Promise<void>;
    updateDispatchStatus(dispatchId: bigint, newStatus: string): Promise<void>;
    updateMasterOrderStatus(totalManufactured: bigint, totalDispatched: bigint): Promise<void>;
    updateProductionStatus(entryId: bigint, newStatus: ContainerStatus): Promise<void>;
}
import type { ContainerStatus as _ContainerStatus, ContainerType as _ContainerType, DispatchEntry as _DispatchEntry, HistoricalOpeningBalance as _HistoricalOpeningBalance, ProductionEntry as _ProductionEntry, Shift as _Shift, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async batchUpdateDailyProductionReport(arg0: string, arg1: Array<DailyReportBatchEntry>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.batchUpdateDailyProductionReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchUpdateDailyProductionReport(arg0, arg1);
            return result;
        }
    }
    async createDailyProductionReport(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDailyProductionReport(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDailyProductionReport(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async createDispatchEntry(arg0: ContainerType, arg1: bigint, arg2: Time, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDispatchEntry(to_candid_ContainerType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDispatchEntry(to_candid_ContainerType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createHistoricalOpeningBalance(arg0: string, arg1: bigint, arg2: bigint, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createHistoricalOpeningBalance(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHistoricalOpeningBalance(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createProductionEntry(arg0: ContainerType, arg1: Shift, arg2: ContainerStatus, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProductionEntry(to_candid_ContainerType_n3(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_ContainerStatus_n5(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProductionEntry(to_candid_ContainerType_n3(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_ContainerStatus_n5(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContainerSizes(): Promise<Array<FrontendContainerSizes>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContainerSizes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContainerSizes();
            return result;
        }
    }
    async getContainerStatuses(): Promise<Array<[ContainerType, ContainerStatus]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContainerStatuses();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContainerStatuses();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContainerTypes(): Promise<Array<ContainerTypes>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContainerTypes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContainerTypes();
            return result;
        }
    }
    async getDailyProductionByStatus(): Promise<Array<[ContainerType, ContainerStatus, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyProductionByStatus();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyProductionByStatus();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyProductionReportsByDate(arg0: string): Promise<Array<DailyProductionReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyProductionReportsByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyProductionReportsByDate(arg0);
            return result;
        }
    }
    async getDailyProductionReportsByDateRange(arg0: string, arg1: string, arg2: [bigint | null, bigint | null]): Promise<Array<DailyProductionReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyProductionReportsByDateRange(arg0, arg1, to_candid_tuple_n18(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyProductionReportsByDateRange(arg0, arg1, to_candid_tuple_n18(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getDailyProductionReportsByOperation(arg0: string): Promise<Array<DailyProductionReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyProductionReportsByOperation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyProductionReportsByOperation(arg0);
            return result;
        }
    }
    async getDispatchEntriesByDate(arg0: Time, arg1: Time): Promise<Array<DispatchEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDispatchEntriesByDate(arg0, arg1);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDispatchEntriesByDate(arg0, arg1);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEnhancedMasterOrderStatus(): Promise<EnhancedMasterOrderStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnhancedMasterOrderStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnhancedMasterOrderStatus();
            return result;
        }
    }
    async getFilteredProductionEntries(arg0: ContainerType | null, arg1: ContainerStatus | null): Promise<Array<ProductionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredProductionEntries(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredProductionEntries(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHistoricalOpeningBalance(): Promise<HistoricalOpeningBalance | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistoricalOpeningBalance();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistoricalOpeningBalance();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMasterOrderStatus(): Promise<MasterOrderStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getMasterOrderStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMasterOrderStatus();
            return result;
        }
    }
    async getMonthlyProductionTotals(arg0: bigint, arg1: bigint): Promise<MonthlyProductionTotals> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyProductionTotals(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyProductionTotals(arg0, arg1);
            return result;
        }
    }
    async getOperationWorkloadSummary(): Promise<Array<OperationStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOperationWorkloadSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOperationWorkloadSummary();
            return result;
        }
    }
    async getProductionSummaryByType(arg0: string, arg1: string, arg2: [bigint | null, bigint | null]): Promise<Array<[bigint, bigint, bigint, bigint, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductionSummaryByType(arg0, arg1, to_candid_tuple_n18(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductionSummaryByType(arg0, arg1, to_candid_tuple_n18(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeContainerTypesAndSizes(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeContainerTypesAndSizes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeContainerTypesAndSizes();
            return result;
        }
    }
    async initializeProductionReports(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeProductionReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeProductionReports();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitOrUpdateDailyReport(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitOrUpdateDailyReport(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitOrUpdateDailyReport(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateDailyProductionReport(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDailyProductionReport(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDailyProductionReport(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateDailyProductionReportById(arg0: bigint, arg1: [bigint | null, bigint | null], arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDailyProductionReportById(arg0, to_candid_tuple_n18(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDailyProductionReportById(arg0, to_candid_tuple_n18(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateDispatchStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDispatchStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDispatchStatus(arg0, arg1);
            return result;
        }
    }
    async updateMasterOrderStatus(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMasterOrderStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMasterOrderStatus(arg0, arg1);
            return result;
        }
    }
    async updateProductionStatus(arg0: bigint, arg1: ContainerStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductionStatus(arg0, to_candid_ContainerStatus_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductionStatus(arg0, to_candid_ContainerStatus_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ContainerStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContainerStatus): ContainerStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ContainerType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContainerType): ContainerType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_DispatchEntry_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DispatchEntry): DispatchEntry {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ProductionEntry_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductionEntry): ProductionEntry {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HistoricalOpeningBalance]): HistoricalOpeningBalance | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    destination: string;
    createdAt: _Time;
    dispatchId: bigint;
    dispatchDate: _Time;
    deliveryStatus: string;
    containerType: _ContainerType;
    quantity: bigint;
}): {
    destination: string;
    createdAt: Time;
    dispatchId: bigint;
    dispatchDate: Time;
    deliveryStatus: string;
    containerType: ContainerType;
    quantity: bigint;
} {
    return {
        destination: value.destination,
        createdAt: value.createdAt,
        dispatchId: value.dispatchId,
        dispatchDate: value.dispatchDate,
        deliveryStatus: value.deliveryStatus,
        containerType: from_candid_ContainerType_n12(_uploadFile, _downloadFile, value.containerType),
        quantity: value.quantity
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ContainerStatus;
    modifiedAt: _Time;
    createdAt: _Time;
    totalQty: bigint;
    entryId: bigint;
    containerType: _ContainerType;
    statusTime: _Time;
    shiftDetail: _Shift;
}): {
    status: ContainerStatus;
    modifiedAt: Time;
    createdAt: Time;
    totalQty: bigint;
    entryId: bigint;
    containerType: ContainerType;
    statusTime: Time;
    shiftDetail: Shift;
} {
    return {
        status: from_candid_ContainerStatus_n14(_uploadFile, _downloadFile, value.status),
        modifiedAt: value.modifiedAt,
        createdAt: value.createdAt,
        totalQty: value.totalQty,
        entryId: value.entryId,
        containerType: from_candid_ContainerType_n12(_uploadFile, _downloadFile, value.containerType),
        statusTime: value.statusTime,
        shiftDetail: value.shiftDetail
    };
}
function from_candid_tuple_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ContainerType, _ContainerStatus]): [ContainerType, ContainerStatus] {
    return [
        from_candid_ContainerType_n12(_uploadFile, _downloadFile, value[0]),
        from_candid_ContainerStatus_n14(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ContainerType, _ContainerStatus, bigint]): [ContainerType, ContainerStatus, bigint] {
    return [
        from_candid_ContainerType_n12(_uploadFile, _downloadFile, value[0]),
        from_candid_ContainerStatus_n14(_uploadFile, _downloadFile, value[1]),
        value[2]
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flatPack: null;
} | {
    fullContainer: null;
} | {
    insulated: null;
}): ContainerType {
    return "flatPack" in value ? ContainerType.flatPack : "fullContainer" in value ? ContainerType.fullContainer : "insulated" in value ? ContainerType.insulated : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    readyForDispatch: null;
} | {
    pendingOperations: null;
} | {
    underTesting: null;
}): ContainerStatus {
    return "readyForDispatch" in value ? ContainerStatus.readyForDispatch : "pendingOperations" in value ? ContainerStatus.pendingOperations : "underTesting" in value ? ContainerStatus.underTesting : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_ContainerType, _ContainerStatus]>): Array<[ContainerType, ContainerStatus]> {
    return value.map((x)=>from_candid_tuple_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_ContainerType, _ContainerStatus, bigint]>): Array<[ContainerType, ContainerStatus, bigint]> {
    return value.map((x)=>from_candid_tuple_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DispatchEntry>): Array<DispatchEntry> {
    return value.map((x)=>from_candid_DispatchEntry_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductionEntry>): Array<ProductionEntry> {
    return value.map((x)=>from_candid_ProductionEntry_n26(_uploadFile, _downloadFile, x));
}
function to_candid_ContainerStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContainerStatus): _ContainerStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ContainerType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContainerType): _ContainerType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContainerType | null): [] | [_ContainerType] {
    return value === null ? candid_none() : candid_some(to_candid_ContainerType_n3(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContainerStatus | null): [] | [_ContainerStatus] {
    return value === null ? candid_none() : candid_some(to_candid_ContainerStatus_n5(_uploadFile, _downloadFile, value));
}
function to_candid_tuple_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint | null, bigint | null]): [[] | [bigint], [] | [bigint]] {
    return [
        to_candid_opt_n19(_uploadFile, _downloadFile, value[0]),
        to_candid_opt_n19(_uploadFile, _downloadFile, value[1])
    ];
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContainerType): {
    flatPack: null;
} | {
    fullContainer: null;
} | {
    insulated: null;
} {
    return value == ContainerType.flatPack ? {
        flatPack: null
    } : value == ContainerType.fullContainer ? {
        fullContainer: null
    } : value == ContainerType.insulated ? {
        insulated: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContainerStatus): {
    readyForDispatch: null;
} | {
    pendingOperations: null;
} | {
    underTesting: null;
} {
    return value == ContainerStatus.readyForDispatch ? {
        readyForDispatch: null
    } : value == ContainerStatus.pendingOperations ? {
        pendingOperations: null
    } : value == ContainerStatus.underTesting ? {
        underTesting: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
